AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/spring.rb'
    - 'config/puma.rb'

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 300

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 69

Metrics/CyclomaticComplexity:
  Max: 18
